### ISSUE TITLE
Add rediness and liveliness props to the deployment spec

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/k8s-ei-operator#11]
**Description:**
Readiness probes are designed to let Kubernetes know when your app is ready to serve traffic. When new configuration applies, Pod will pull the base image according to the image pull policy and restart the pod. 

Here the issue is if a user sends a request while restarting k8s will response as connection refuse error. Need to avoid this from adding readiness and liveliness props into the deployment spec. 

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
We introduced an internal API to check the readiness of the pod.
The following is the configuration used in deployment.yaml file
```
 readinessProbe:
     httpGet:
         path: /healthz
         port: 9201
     initialDelaySeconds: 5
     periodSeconds: 2 
```
This is available from 1.2.0-m1
